In [15]:
from numpy.random import choice
from typing import List
import pandas as pd

x = ['Louis Agassiz', 'Maria Gaetana Agnesi', 'Al-Battani', 'Abu Nasr Al-Farabi',
        'Alhazen', 'Jim Al-Khalili',
        'Muhammad ibn Musa al-Khwarizmi',
        'Mihailo Petrovic Alas',
        'Angel Alcala', 'Salim Ali', 'Luis Alvarez',
        'Andre Marie AmpÃ¨re', 'Anaximander',
        'Carl Anderson', 'Mary Anning',
        'Virginia Apgar', 'Archimedes',
        'Agnes Arber', 'Aristarchus',
        'Aristotle', 'Svante Arrhenius',
        'Oswald Avery', 'Amedeo Avogadro', 'Avicenna', 'Blaise Pascal' 'Louis Pasteur',
        'Wolfgang Ernst Pauli',
        'Linus Pauling',
        'Randy Pausch',
        'Ivan Pavlov',
        'Cecilia Payne-Gaposchkin',
        'Wilder Penfield',
        'Marguerite Perey',
        'William Perkin',
        'John Philoponus',
        'Jean Piaget',
        'Philippe Pinel',
        'Max Planck',
        'Pliny the Elder',
        'Karl Popper',
        'Beatrix Potter',
        'Joseph Priestley',
        'Proclus',
        'Claudius Ptolemy',
        'Pythagoras', 'Niccolo Tartaglia',
        'Edward Teller',
        'Nikola Tesla',
        'Thales of Miletus',
        'Theon of Alexandria',
        'Benjamin Thompson',
        'J. J. Thomson',
        'William Thomson',
        'Henry David Thoreau',
        'Kip S. Thorne',
        'Clyde Tombaugh',
        'Susumu Tonegawa',
        'Evangelista Torricelli',
        'Charles Townes',
        'Youyou Tu',
        'Alan Turing',
        'Neil deGrasse Tyson']

def set_names(dat: pd.DataFrame, names: List[str] = x) -> pd.DataFrame: 
    return dat.rename(index={k: choice(names) for k in range(dat.shape[0])})

set_names(pd.read_csv('survey_.csv', sep='\t')).to_csv('survey.csv', index_label='Unnamed: 0')

In [16]:
pd.read_csv('survey.csv')

,Unnamed: 0,What is your programming level?,What is your math level?,What level are you going to be when you finish Data Science at Lambda School? ðŸ˜€,In a classroom I
0,Evangelista Torricelli,6.0,8.0,10.0,just listen and take notes
1,Pythagoras,1.0,3.0,9.0,just listen and take notes
2,Alhazen,3.0,3.0,10.0,just listen and take notes
3,Randy Pausch,8.0,8.0,9.0,just listen and take notes
4,Alhazen,NaN,NaN,NaN,NaN
5,Wilder Penfield,2.0,3.0,10.0,just listen and take notes
6,Claudius Ptolemy,3.0,5.0,10.0,just listen and take notes
7,Jean Piaget,10.0,10.0,10.0,just listen and take notes
8,Claudius Ptolemy,3.0,5.0,10.0,just listen and take notes
9,Clyde Tombaugh,2.0,6.0,10.0,ask a lot of questions
10,Joseph Priestley,5.0,9.0,10.0,ask a lot of questions
11,Evangelista Torricelli,4.0,5.0,10.0,ask a lot of questions
12,Beatrix Potter,6.0,6.0,10.0,just listen and take notes
13,Wilder Penfield,1.0,2.0,10.0,ask a lot of questions
14,Louis Agassiz,6.0,8.0,10.0,just listen and take notes
15,Luis Alvarez,4.0,6.0,10.0,ask a lot of questions
16,Svante Arrhenius,2.0,6.0,10.0,just listen and take notes
17,Louis Agassiz,1.0,9.0,9.0,just listen and take notes
18,John Philoponus,3.0,3.0,10.0,just listen and take notes
19,Charles Townes,3.0,3.0,10.0,just listen and take notes
20,John Philoponus,1.0,7.0,10.0,just listen and take notes
21,Wilder Penfield,1.0,7.0,10.0,ask a lot of questions
22,Niccolo Tartaglia,5.0,5.0,9.0,ask a lot of questions
23,Abu Nasr Al-Farabi,3.0,6.0,9.0,just listen and take notes
24,Clyde Tombaugh,5.0,6.0,10.0,just listen and take notes
25,Niccolo Tartaglia,6.0,6.0,10.0,ask a lot of questions
26,Charles Townes,1.0,4.0,6.0,ask a lot of questions
27,Alan Turing,3.0,4.0,10.0,just listen and take notes
28,Joseph Priestley,5.0,6.0,10.0,just listen and take notes
29,Archimedes,4.0,7.0,10.0,just listen and take notes